#!/usr/bin/env bash
set -e
FILE=$1

# Check that $FILE is not --help or -h
if [ -z "$FILE" ] || [ "$FILE" == "--help" ] || [ "$FILE" == "-h" ]; then
    echo "Usage: gh-find-file <file>"
    exit 1
fi

for branch in $(git branch --all | sed 's/\*//' | sed 's/-> .*//'); do
    # Check if the file exists in the branch
    
    if git ls-tree --name-only -r "$branch"  | grep --quiet "$FILE"; then
        echo "$FILE found in $branch"
    fi
done